FROM registry.redhat.io/rhel9/rhel-bootc:9.6

RUN dnf -y install httpd

ADD etc/ /etc

RUN <<EOF 
    set -euxo pipefail
    mv /var/www /usr/share/www
    sed -i 's-/var/www-/usr/share/www-' /etc/httpd/conf/httpd.conf
EOF
    
COPY html/index.html /usr/share/www/html/index.html
COPY html/style.css /usr/share/www/html/style.css
COPY html/osrelease.js /usr/share/www/html/osrelease.js
RUN cp /etc/os-release /usr/share/www/html/os-release

RUN systemctl enable httpd 

EXPOSE 80
